[metadata]
addr = 0x4a705
size = 0x6b
last_change = 2024-04-11T12:30:11.873875Z

[header]
last_change = 2024-04-11T12:30:11.873875Z
name = "michael_is_cool"
addr = 0x4a705
type = "long long"

[stack_vars.-0x40]
offset = -32
name = "v24"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x38]
offset = -24
name = "v25"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x30]
offset = -16
name = "v26"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x28]
offset = -8
name = "v27"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x20]
offset = 0x0
name = "v28"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x18]
offset = 0x8
name = "v29"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x10]
offset = 0x10
name = "v30"
type = "long long"
size = 0x8
addr = 0x4a705

[stack_vars.-0x8]
offset = 0x18
name = "v31"
type = "long long"
size = 0x8
addr = 0x4a705

[header.args.0]
offset = 0x0
name = "a4"
type = "long long"
size = 0x8

[header.args.1]
offset = 0x1
name = "a6"
type = "unsigned long long"
size = 0x8

[header.args.2]
offset = 0x2
name = "a1"
type = "long long"
size = 0x8

[header.args.3]
offset = 0x3
name = "a2"
type = "long long"
size = 0x8

[header.args.4]
offset = 0x4
name = "a3"
type = "long long"
size = 0x8

[header.args.5]
offset = 0x5
name = "a5"
type = "long long"
size = 0x8
