[metadata]
addr = 0x4a522
size = 0x3e
last_change = 2024-04-11T09:51:02.476689Z

[header]
last_change = 2024-04-11T09:51:02.476689Z
name = "pissy_func"
addr = 0x4a522
type = "int *"

[header.args.0]
offset = 0x0
name = "a1"
type = "_DWORD *"
size = 0x8

[header.args.1]
offset = 0x1
name = "a2"
type = "long long"
size = 0x8

[header.args.2]
offset = 0x2
name = "a3"
type = "long long"
size = 0x8

[header.args.3]
offset = 0x3
name = "a4"
type = "unsigned int"
size = 0x4
