[0x4a4f6]
addr = 0x4a4f6
func_addr = 0x4a4f0
comment = "poopie comment\n"
decompiled = false

[0x4a505]
last_change = 2024-04-11T12:39:43.601534Z
addr = 0x4a505
func_addr = 0x4a4f0
comment = "some xor...\n"
decompiled = false

[0x4a57e]
last_change = 2024-04-11T12:19:11.845637Z
addr = 0x4a57e
func_addr = 0x4a560
comment = "-1\n"
decompiled = false

[0x4a72d]
last_change = 2024-04-11T12:26:48.570578Z
addr = 0x4a72d
func_addr = 0x4a705
comment = "LINUX - sys_mmap\n"
decompiled = false
