[0x4a4f0]
last_change = 2024-04-11T13:22:57.027555Z
addr = 0x4a4f0
func_addr = 0x4a4f0
comment = "cool comment in the decompiler\n"
decompiled = true

[0x4a4f6]
last_change = 2024-04-11T09:50:50.763789Z
addr = 0x4a4f6
func_addr = 0x4a4f0
comment = "poopie comment\n"
decompiled = false

[0x4a505]
addr = 0x4a505
func_addr = 0x4a4f0
comment = "some xor...\n"
decompiled = false

[0x4a512]
addr = 0x4a512
func_addr = 0x4a4f0
comment = "1111111\n"
decompiled = false

[0x4a57e]
addr = 0x4a57e
func_addr = 0x4a560
comment = "-1\n"
decompiled = false

[0x4a582]
last_change = 2024-04-11T13:11:44.457828Z
addr = 0x4a582
func_addr = 0x4a560
comment = "aaaaa\n"
decompiled = false

[0x4a72d]
addr = 0x4a72d
func_addr = 0x4a705
comment = "LINUX - sys_mmap\n"
decompiled = false
